services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_city_db
    environment:
      POSTGRES_DB: smart_city
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smart_city"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
